nxp: Resolve unused variables and errors
 * src/phLibNfc_llcp.c:74:22:
    error: comparison between pointer and integer

 * src/phLibNfc_discovery.c:369:27:
    error: variable 'response' used in loop
    condition not modified in loop body

 * src/phLibNfc_initiator.c:328:20:
    error: explicitly assigning value of
    variable of type 'NFCSTATUS'

 * src/phFriNfc_Llcp.c:
    843:37: error: unused variable 'sHeader'
    927:1: error: unused label 'clean_and_return'

 * src/phFriNfc_LlcpTransport.c:
    1807:12: error: unused variable 'i'
    1897:12: error: unused variable 'i'

 * src/phFriNfc_LlcpTransport_Connection.c:
    50:39: error: unused variable 'psLocalLlcpSocket'
    51:38: error: unused variable 'sFrmrBuffer'
    52:38: error: unused variable 'index'
    53:38: error: unused variable 'socketFound'
    1612:14: error: unused variable 'index'

 * src/phFriNfc_LlcpTransport_Connectionless.c:
    135:46: error: unused variable 'pSavedContext'

 * src/phFriNfc_MifareStdMap.c: 3750:51: error:
    equality comparison with extraneous parentheses

 * src/phFriNfc_MifareULMap.c:3062:51: error:
    equality comparison with extraneous parentheses

 * src/phFriNfc_TopazMap.c: 280:33, 364:33, 446:33,
    929:33, 958:33, 996:33, 1089:29, 1173:33:
     error: implicit conversion from enumeration
     type 'enum phHal_eJewelCmdList'

 * src/phFriNfc_FelicaMap.c: 770:27, 980:31,
    1178:27, 2098:27, 2170:27, 2733:27:
     error: implicit conversion from enumeration
     type 'enum phHal_eJewelCmdList'
    2249:33: error: ordered comparison between
     pointer and integer

 * src/phFriNfc_DesfireMap.c:1185:35: error:
    equality comparison with extraneous parentheses

 * src/phFriNfc_TopazDynamicMap.c:1816:31, 1970:31:
    error: implicit conversion from enumeration
    type 'enum phHal_eJewelCmdList'

 * src/phFriNfc_DesfireFormat.c:694:75, 714:33, 783:33:
    error: equality comparison with extraneous parentheses

 * src/phFriNfc_ISO15693Format.c:547:38:
    error: unused variable 'ps_iso15693_info'

 * src/phFriNfc_OvrHal.c:338:28, 403:29:
    error: explicitly assigning value of variable of type
    'phHal_sRemoteDevInformation_t *' to itself

 * Linux_x86/phDal4Nfc.c:
    293:11: error: unused variable pThreadReturn
    539:12: error: unused variable num_eeprom_settings
    540:13: error: unused variable eeprom_settings
    708:15: error: unused variable retvalue
    709:15: error: unused variable result
    710:15: error: unused variable retry_cnt
    718:9: error: unused variable i
    836:20: error: unused variable nReadThreadAttributes
    837:20: error: unused variable nWriteThreadAttributes
    914:13: error: unused variable i

 * src/phFriNfc_NdefRecord.c:
    229:18: error: implicit declaration of
     function 'phFriNfc_NdefRecord_RecordIDCheck'
    492:25: error: implicit declaration of
     function 'phFriNfc_NdefRecord_RecordFlag'
    496:15: error: implicit declaration of
     function 'phFriNfc_NdefRecord_TypeNameFormat'

Change-Id: I181bd41dcb0ca8071cc2a4ce4b4d46c99e1775f9